python gridsearch/summarize_gridsearch.py outputs/iid/L2_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/instance/L2_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/class_instance/L2_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/class_iid/L2_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/iid/EWC_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/instance/EWC_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/class_instance/EWC_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/class_iid/EWC_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/iid/MAS_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/instance/MAS_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/class_instance/MAS_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/class_iid/MAS_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/iid/SI_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/instance/SI_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/class_instance/SI_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/class_iid/SI_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/iid/NaiveRehearsal_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/instance/NaiveRehearsal_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/class_instance/NaiveRehearsal_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/class_iid/NaiveRehearsal_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/iid/GEM_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/instance/GEM_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/class_instance/GEM_gridsearch &
python gridsearch/summarize_gridsearch.py outputs/class_iid/GEM_gridsearch &
