python gridsearch.py EWC 1
python gridsearch.py L2 1
python gridsearch.py MAS 1
python gridsearch.py SI 1
python gridsearch.py iCARL 1
python gridsearch.py NaiveRehearsal 1
python gridsearch.py GEM 1
python gridsearch.py NormalNNlower 1
python gridsearch.py NormalNNupper 1
