python -u experiment.py --scenario class_iid --n_runs 2 --model_type resnet --model_name ResNet18 --agent_type exp_replay --agent_name NaiveRehearsal --optimizer SGD --batch_size 20 --lr 0.001 --momentum 0.9 --weight_decay 0.0001 --pretrained --n_epoch 1 --reg_coef 1.0 --memory_size 15 --dataroot /media/data/morgan_data/toybox/images --filelist_root dataloaders --dataset toybox --output_dir toybox_gridsearch_outputs --n_workers 20 --gpuid 3 --validate --custom_folder NaiveRehearsal/lr-0.001/ | tee ./toybox_gridsearch_outputs/class_iid/NaiveRehearsal/lr-0.001/log.log
wait 
python -u experiment.py --scenario class_iid --n_runs 2 --model_type resnet --model_name ResNet18 --agent_type exp_replay --agent_name NaiveRehearsal --optimizer SGD --batch_size 20 --lr 0.0001 --momentum 0.9 --weight_decay 0.0001 --pretrained --n_epoch 1 --reg_coef 1.0 --memory_size 15 --dataroot /media/data/morgan_data/toybox/images --filelist_root dataloaders --dataset toybox --output_dir toybox_gridsearch_outputs --n_workers 20 --gpuid 3 --validate --custom_folder NaiveRehearsal/lr-0.0001/ | tee ./toybox_gridsearch_outputs/class_iid/NaiveRehearsal/lr-0.0001/log.log
wait 
python -u experiment.py --scenario class_iid --n_runs 2 --model_type resnet --model_name ResNet18 --agent_type exp_replay --agent_name NaiveRehearsal --optimizer SGD --batch_size 20 --lr 1e-05 --momentum 0.9 --weight_decay 0.0001 --pretrained --n_epoch 1 --reg_coef 1.0 --memory_size 15 --dataroot /media/data/morgan_data/toybox/images --filelist_root dataloaders --dataset toybox --output_dir toybox_gridsearch_outputs --n_workers 20 --gpuid 3 --validate --custom_folder NaiveRehearsal/lr-1e-05/ | tee ./toybox_gridsearch_outputs/class_iid/NaiveRehearsal/lr-1e-05/log.log
wait 
python -u experiment.py --scenario class_instance --n_runs 2 --model_type resnet --model_name ResNet18 --agent_type exp_replay --agent_name NaiveRehearsal --optimizer SGD --batch_size 20 --lr 0.001 --momentum 0.9 --weight_decay 0.0001 --pretrained --n_epoch 1 --reg_coef 1.0 --memory_size 15 --dataroot /media/data/morgan_data/toybox/images --filelist_root dataloaders --dataset toybox --output_dir toybox_gridsearch_outputs --n_workers 20 --gpuid 3 --validate --custom_folder NaiveRehearsal/lr-0.001/ | tee ./toybox_gridsearch_outputs/class_instance/NaiveRehearsal/lr-0.001/log.log
wait 
python -u experiment.py --scenario class_instance --n_runs 2 --model_type resnet --model_name ResNet18 --agent_type exp_replay --agent_name NaiveRehearsal --optimizer SGD --batch_size 20 --lr 0.0001 --momentum 0.9 --weight_decay 0.0001 --pretrained --n_epoch 1 --reg_coef 1.0 --memory_size 15 --dataroot /media/data/morgan_data/toybox/images --filelist_root dataloaders --dataset toybox --output_dir toybox_gridsearch_outputs --n_workers 20 --gpuid 3 --validate --custom_folder NaiveRehearsal/lr-0.0001/ | tee ./toybox_gridsearch_outputs/class_instance/NaiveRehearsal/lr-0.0001/log.log
wait 
python -u experiment.py --scenario class_instance --n_runs 2 --model_type resnet --model_name ResNet18 --agent_type exp_replay --agent_name NaiveRehearsal --optimizer SGD --batch_size 20 --lr 1e-05 --momentum 0.9 --weight_decay 0.0001 --pretrained --n_epoch 1 --reg_coef 1.0 --memory_size 15 --dataroot /media/data/morgan_data/toybox/images --filelist_root dataloaders --dataset toybox --output_dir toybox_gridsearch_outputs --n_workers 20 --gpuid 3 --validate --custom_folder NaiveRehearsal/lr-1e-05/ | tee ./toybox_gridsearch_outputs/class_instance/NaiveRehearsal/lr-1e-05/log.log
